version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    command: ["npm", "start"]
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paiement
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  mongo:
    image: mongo:6
    volumes:
      - mongodata:/data/db
    ports:
      - '27018:27017'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '8080:80'

volumes:
  pgdata:
  mongodata:
